language: python

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'gcc-4.9', 'gfortran-4.9']
      env:
        - CXX='g++-4.9'
        - CC='gcc-4.9'
        - FC='gfortran-4.9'
      python: 3.6

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install
  - pipenv run python -m encodertb.pyencoder.builder

# command to run tests
script: pytest