language: python
cache:
  - ccache
  - pip

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.9']
      env:
        - CC='gcc-4.9'
      python: 3.6

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install
  - pipenv run python -m encodertb.pyencoder.builder

# command to run tests
script: pipenv run python -m pytest