language: python
python: 3.6
dist: xenial
cache:
  - ccache
  - pip


# command to install dependencies
install:
  - pip install pipenv
  - pipenv install
  - pipenv run python -m encodertb.pyencoder.builder

# command to run tests
script: pipenv run python -m pytest