var files_dup =
[
    [ "base64.c", "base64_8c.html", "base64_8c" ],
    [ "base64.h", "base64_8h.html", "base64_8h" ],
    [ "batv.c", "batv_8c.html", "batv_8c" ],
    [ "batv.h", "batv_8h.html", "batv_8h" ],
    [ "defs.h", "defs_8h.html", "defs_8h" ],
    [ "eep.c", "eep_8c.html", "eep_8c" ],
    [ "eep.h", "eep_8h.html", "eep_8h" ],
    [ "md5.c", "md5_8c.html", "md5_8c" ],
    [ "md5.h", "md5_8h.html", "md5_8h" ],
    [ "ndef.c", "ndef_8c.html", "ndef_8c" ],
    [ "ndef.h", "ndef_8h.html", "ndef_8h" ],
    [ "nt3h.c", "nt3h_8c.html", "nt3h_8c" ],
    [ "nt3h.h", "nt3h_8h.html", "nt3h_8h" ],
    [ "nvtype.c", "nvtype_8c.html", "nvtype_8c" ],
    [ "nvtype.h", "nvtype_8h.html", "nvtype_8h" ],
    [ "octet.c", "octet_8c.html", "octet_8c" ],
    [ "octet.h", "octet_8h.html", "octet_8h" ],
    [ "prng.c", "prng_8c.html", "prng_8c" ],
    [ "prng.h", "prng_8h.html", "prng_8h" ],
    [ "sample.c", "sample_8c.html", "sample_8c" ],
    [ "sample.h", "sample_8h.html", "sample_8h" ],
    [ "smplhist.c", "smplhist_8c.html", "smplhist_8c" ],
    [ "smplhist.h", "smplhist_8h.html", "smplhist_8h" ]
];