#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   Issue #350 is still open: on Windows, the code here causes it to link
   with PYTHON36.DLL (for example) instead of PYTHON3.DLL.  A fix was
   attempted in 164e526a5515 and 14ce6985e1c3, but reverted: virtualenv
   does not make PYTHON3.DLL available, and so the "correctly" compiled
   version would not run inside a virtualenv.  We will re-apply the fix
   after virtualenv has been fixed for some time.  For explanation, see
   issue #355.  For a workaround if you want PYTHON3.DLL and don't worry
   about virtualenv, see issue #350.  See also 'py_limited_api' in
   setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  include <pyconfig.h>
#  if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG)
#    define Py_LIMITED_API
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t(x);
}


/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

#include "eep.h"
#include "octet.h"
#include "defs.h"

#define OCTET_TO_BLK(octet) (_startblk + (octet >> 1))
#define MAX_CURSOROCTET  (_lenoctets - 1)


static int _endblk = 0;
static int _startblk = 0;

static int _cursorblk;
static int _nextblk;

static int _lenoctets = 0;
static int _cursoroctet = 0;
static OctState_t _octetstate = firstloop;

// Read 4 octets from cursor block.
static int octet_read4(const int cursorblk)
{
  int looparound = 0;

  if (cursorblk == _endblk)
  {
    _cursorblk = cursorblk;
    _nextblk = _startblk;
    looparound = 1;
  }
  else
  {
    _cursorblk = cursorblk;
    _nextblk = _cursorblk + 1;
  }

  eep_read(_cursorblk, 0);
  eep_read(_nextblk, 1);

  return looparound;
}

void octet_restore(void)
{
  octet_read4(_cursorblk);
}

// Initialise a circular buffer of octets between startblk and endblk.
int octet_init(const int startblk, const int lenblks)
{
  _startblk = startblk;
  _endblk = startblk+lenblks-1;

  _cursorblk = startblk;
  _nextblk = _cursorblk + 1;

  // Calculate the number of octets.
  _lenoctets = lenblks*OCTETS_PER_BLK;
  _cursoroctet = 0;
  _octetstate = firstloop;

  octet_read4(startblk);

  return 0;
}

int octet_commit4(void)
{
  eep_write(_cursorblk, 0);
  eep_write(_nextblk, 1);
  eep_waitwritedone();

  return 0;
}

int octet_commit2(void)
{
  eep_write(_nextblk, 1);
  eep_waitwritedone();

  return 0;
}

// Octet index is relative to cursoroctet.
int octet_write(OctInd_t octetindex, char * octetdata)
{
  int errflag = 1;
  int octetstart;
  int octindex = (int)octetindex;
  // If cursoroctet is odd, then octetstart is at 1.
  // If cursoroctet is even, then octetstart is at 0.
  // Octet index must be 0, 1 or 2.
  if ((_cursoroctet & 0x01) > 0)
  {
    // ODD. octetindex range is 1,2,3
    octindex += 1;
  }

  errflag = 0;
  octetstart = octindex * BYTES_PER_OCTET;
  // Copy data to the buffer
  errflag = eep_cp(&octetstart, octetdata, BYTES_PER_OCTET);

  return errflag;
}

// Move cursor forward by 1. Add overwriting and looping around as parameters.
int octet_movecursor(void)
{
  int cursorblk;
  int looparound = 0;

  // Increment _cursoroctet
  if (_cursoroctet == MAX_CURSOROCTET)
  {
    _cursoroctet = 0;
  }
  else
  {
    _cursoroctet = _cursoroctet + 1;
  }

  // Determine if a read is needed.
  cursorblk = OCTET_TO_BLK(_cursoroctet);
  if (cursorblk != _cursorblk)
  {
    // Perform a read.
    // Only raise the looparound flag once per loop,
    // when the last octet will be written to the first octet of the first block.
    looparound = octet_read4(cursorblk);
  }

  switch(_octetstate)
  {
    case firstloop:
    if (looparound == 1)
    {
      _octetstate = loopingaround;
    }
    break;
    case loopingaround:
    _octetstate = overwriting;
    break;
    case overwriting:
    if (looparound == 1)
    {
      _octetstate = loopingaround;
    }
    break;
  }

  return 0;
}

OctState_t octet_getstate(void)
{
  return _octetstate;
}
#include "ndef.h"
#include "base64.h"
#include "eep.h"
#include "defs.h"
#include "nvtype.h"

extern nv_t nv;

#define URL_RECORDTYPE      0x55
#define URL_RECORDTYPE_LEN  1

#define TLV_START       0x03

#define WELLKNOWN_TNF   0x01
#define ABSURI_TNF      0x03
#define UNCHANGED_TNF   0x06

#define URI_ID_HTTP     0x03
#define URI_ID_HTTPS    0x04

typedef union
{
 unsigned char all;
 struct
 {
     unsigned char tnf:3;
     unsigned char idpresent:1;
     unsigned char srecord:1;
     unsigned char chunkflag:1;
     unsigned char msgend:1;
     unsigned char msgbegin:1;
 } byte;
} RecordHeader_t;

typedef union
{
    unsigned long all;
    unsigned char bytes[4];
} len_t;

char serialparam[] = "&s=";
static const char queryparam[] = "&q=";
static const char verparam[] = "&v=0";
static char _ver = 0;
static const char statparam[] = "&x=";
static const char timeintparam[] = "t=";
static const char url[] = "plotsensor.com/?";
static const char zeropad[] = "MDAw";

static void ndef_createurlrecord(int * eepindex, int msglenbytes)
{
    RecordHeader_t rheader;
    len_t payloadLength;

    int recordType = URL_RECORDTYPE;
    int typeLength;
    int idLength;

    int id = 1;

    rheader.all = 0xD1;
    rheader.byte.chunkflag = 0;
    rheader.byte.msgend = 1;
    rheader.byte.idpresent = 0;
    rheader.byte.srecord = 0;
    rheader.byte.msgbegin = 1;
    rheader.byte.tnf = WELLKNOWN_TNF;
    typeLength = URL_RECORDTYPE_LEN;
    idLength = 1;

    payloadLength.all = msglenbytes-7;

    eep_cpbyte(eepindex, rheader.all); // Record header
    eep_cpbyte(eepindex, typeLength);
    eep_cpbyte(eepindex, payloadLength.bytes[3]);
    eep_cpbyte(eepindex, payloadLength.bytes[2]);
    eep_cpbyte(eepindex, payloadLength.bytes[1]);
    eep_cpbyte(eepindex, payloadLength.bytes[0]);
    if (rheader.byte.idpresent == 1)
    {
        eep_cpbyte(eepindex, idLength);
    }

    if (typeLength > 0)
    {
        eep_cpbyte(eepindex, recordType);
    }

    if (rheader.byte.idpresent == 1)
    {
        eep_cpbyte(eepindex, id);
    }

    eep_cpbyte(eepindex, URI_ID_HTTPS); // WWW or FTP
}

int ndef_writepreamble(int qlenblks, char * statusb64)
{
  int msglenbytes = ((qlenblks + PREAMBLEN_BLKS) * BLKSIZE_BYTES) - TLSIZE_BYTES;
  char timeintb64[5] = {0};
  int errflag = 0;
  int blk;
  int eepindex = 0;
  char * serial = nv.serial;
  char timeinterval = nv.smplintervalmins;

  /* qlenblks must be even */
  if ((qlenblks & 0x01) != 0)
  {
      errflag = 1;
  }

  // TLV Message Type
  eep_cpbyte(&eepindex, TLV_START);

  // TLV Message Length
  eep_cpbyte(&eepindex, 0xFF);
  eep_cpbyte(&eepindex, ((msglenbytes & 0xFF00) >> 8));
  eep_cpbyte(&eepindex, (msglenbytes & 0x00FF)); //Remove 0xFE TLV start, TLV length and TLV end. That is 3 bytes in all.

  // Start NDEF record
  ndef_createurlrecord(&eepindex, msglenbytes);

  Base64encode(timeintb64, &timeinterval, 2);

  // Append URL
  eep_cp(&eepindex, url, sizeof(url)-1);
  // Append time interval header
  eep_cp(&eepindex, timeintparam, sizeof(timeintparam)-1);
  // Append time interval value
  eep_cp(&eepindex, timeintb64, sizeof(timeintb64)-1);
  // Append serial param
  eep_cp(&eepindex, serialparam, sizeof(serialparam)-1);
  // Append serial
  eep_cp(&eepindex, serial, SERIAL_LENBYTES);
  // Append version param
  eep_cp(&eepindex, verparam, sizeof(verparam)-1);
  // Append version
  eep_cp(&eepindex, &_ver, 1);
  // Append status header
  eep_cp(&eepindex, statparam, sizeof(statparam)-1);
  // Append status data
  eep_cp(&eepindex, statusb64, 8);
  // Append padding
  //ndef_append(&blkptr, padparam);
  // Append query string
  eep_cp(&eepindex, queryparam, sizeof(queryparam)-1);

  //ndef_pad(&blkptr, endptr);

  // Write the first 64 bytes to memory.
  for(blk=0; blk<PREAMBLEN_BLKS; blk++)
  {
      eep_write(blk, blk);
  }

  eep_waitwritedone();

  return errflag;
}


int ndef_writeblankurl(int qlenblks, char * statusb64, int * qstartblk, char ver)
{
    int eepindex;
    int i, blk, errflag;

    _ver = ver;

    errflag = ndef_writepreamble(qlenblks, statusb64);

    *qstartblk = PREAMBLEN_BLKS;

    // Write 2 blocks of padding.
    eepindex = 0;
    for(i=0; i<4; i++)
    {
      eep_cp(&eepindex, zeropad, sizeof(zeropad)-1);
    }

    // Populate the q parameter with padding.
    for(blk=0; blk<qlenblks; blk++)
    {
        eep_write(*qstartblk + blk, 0);
    }

    eep_waitwritedone();

    return errflag;
}
#include "eep.h"
#include "nt3h.h"

#define BUFSIZE_BLKS  4
#define BUFSIZE_BYTES (BUFSIZE_BLKS * BLKSIZE)

char _blkbuffer[BUFSIZE_BLKS * BLKSIZE] = {0};

static inline int inbounds(int byteindex)
{
  return ((byteindex >= 0) && (byteindex < BUFSIZE_BYTES));
}

int eep_write(const int eepblk, const unsigned int bufblk)
{
  int errflag = 1;
  int startbyte = bufblk * BLKSIZE;
  if (bufblk < BUFSIZE_BLKS)
  {
    nt3h_writetag(eepblk+1, &_blkbuffer[startbyte]);
    errflag = 0;
  }

  return errflag;
}

void eep_waitwritedone()
{
    while(nt3h_eepromwritedone() != 0);
}

int eep_read(const int eepblk, const unsigned int bufblk)
{
  int errflag = 1;
  int startbyte = bufblk * BLKSIZE;
  if (bufblk < BUFSIZE_BLKS)
  {
    nt3h_readtag(eepblk+1, &_blkbuffer[startbyte]);
    errflag = 0;
  }

  return errflag;
}

int eep_cp(int * indexptr, const char * dataptr, const int lenbytes)
{
  int startbyte = *indexptr;
  int endbyte = startbyte + lenbytes - 1;
  int errflag = 1;
  int i;

  if (inbounds(startbyte) && inbounds(endbyte))
  {
    for (i=0; i<lenbytes; i++)
    {
      _blkbuffer[startbyte + i] = *(dataptr + i);
    }
    *indexptr = endbyte + 1;
    errflag = 0;
  }

  return errflag;
}

int eep_cpbyte(int * indexptr, const char bytedata)
{
  int errflag = 1;

  if (inbounds(*indexptr))
  {
    _blkbuffer[*indexptr] = bytedata;
    (*indexptr) = (*indexptr) + 1;
    errflag = 0;
  }

  return errflag;
}
/*
 * Copyright (c) 2003 Apple Computer, Inc. All rights reserved.
 *
 * @APPLE_LICENSE_HEADER_START@
 *
 * Copyright (c) 1999-2003 Apple Computer, Inc.  All Rights Reserved.
 *
 * This file contains Original Code and/or Modifications of Original Code
 * as defined in and that are subject to the Apple Public Source License
 * Version 2.0 (the 'License'). You may not use this file except in
 * compliance with the License. Please obtain a copy of the License at
 * http://www.opensource.apple.com/apsl/ and read it before using this
 * file.
 *
 * The Original Code and all software distributed under the License are
 * distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER
 * EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
 * INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.
 * Please see the License for the specific language governing rights and
 * limitations under the License.
 *
 * @APPLE_LICENSE_HEADER_END@
 */
/* ====================================================================
 * Copyright (c) 1995-1999 The Apache Group.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgment:
 *    "This product includes software developed by the Apache Group
 *    for use in the Apache HTTP server project (http://www.apache.org/)."
 *
 * 4. The names "Apache Server" and "Apache Group" must not be used to
 *    endorse or promote products derived from this software without
 *    prior written permission. For written permission, please contact
 *    apache@apache.org.
 *
 * 5. Products derived from this software may not be called "Apache"
 *    nor may "Apache" appear in their names without prior written
 *    permission of the Apache Group.
 *
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by the Apache Group
 *    for use in the Apache HTTP server project (http://www.apache.org/)."
 *
 * THIS SOFTWARE IS PROVIDED BY THE APACHE GROUP ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE APACHE GROUP OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * ====================================================================
 *
 * This software consists of voluntary contributions made by many
 * individuals on behalf of the Apache Group and was originally based
 * on public domain software written at the National Center for
 * Supercomputing Applications, University of Illinois, Urbana-Champaign.
 * For more information on the Apache Group and the Apache HTTP server
 * project, please see <http://www.apache.org/>.
 *
 */

/* Base64 encoder/decoder. Originally Apache file ap_base64.c
 */

#include <string.h>

#include "base64.h"

/* aaaack but it's fast and const should make it shared text page. */
static const unsigned char pr2six[256] =
{
    /* ASCII table */
    64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
    64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
    64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 62, 64, 64, 64, 63,
    52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 64, 64, 64, 64, 64, 64,
    64,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
    15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 64, 64, 64, 64, 64,
    64, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
    41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 64, 64, 64, 64, 64,
    64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
    64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
    64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
    64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
    64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
    64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
    64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
    64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64
};

int Base64decode_len(const char *bufcoded)
{
    int nbytesdecoded;
    register const unsigned char *bufin;
    register int nprbytes;

    bufin = (const unsigned char *) bufcoded;
    while (pr2six[*(bufin++)] <= 63);

    nprbytes = (bufin - (const unsigned char *) bufcoded) - 1;
    nbytesdecoded = ((nprbytes + 3) / 4) * 3;

    return nbytesdecoded + 1;
}

int Base64decode(char *bufplain, const char *bufcoded)
{
    int nbytesdecoded;
    register const unsigned char *bufin;
    register unsigned char *bufout;
    register int nprbytes;

    bufin = (const unsigned char *) bufcoded;
    while (pr2six[*(bufin++)] <= 63);
    nprbytes = (bufin - (const unsigned char *) bufcoded) - 1;
    nbytesdecoded = ((nprbytes + 3) / 4) * 3;

    bufout = (unsigned char *) bufplain;
    bufin = (const unsigned char *) bufcoded;

    while (nprbytes > 4) {
    *(bufout++) =
        (unsigned char) (pr2six[*bufin] << 2 | pr2six[bufin[1]] >> 4);
    *(bufout++) =
        (unsigned char) (pr2six[bufin[1]] << 4 | pr2six[bufin[2]] >> 2);
    *(bufout++) =
        (unsigned char) (pr2six[bufin[2]] << 6 | pr2six[bufin[3]]);
    bufin += 4;
    nprbytes -= 4;
    }

    /* Note: (nprbytes == 1) would be an error, so just ingore that case */
    if (nprbytes > 1) {
    *(bufout++) =
        (unsigned char) (pr2six[*bufin] << 2 | pr2six[bufin[1]] >> 4);
    }
    if (nprbytes > 2) {
    *(bufout++) =
        (unsigned char) (pr2six[bufin[1]] << 4 | pr2six[bufin[2]] >> 2);
    }
    if (nprbytes > 3) {
    *(bufout++) =
        (unsigned char) (pr2six[bufin[2]] << 6 | pr2six[bufin[3]]);
    }

    *(bufout++) = '\0';
    nbytesdecoded -= (4 - nprbytes) & 3;
    return nbytesdecoded;
}

static const char basis_64[] =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";

int Base64encode_len(int len)
{
    return ((len + 2) / 3 * 4) + 1;
}

int Base64encode(char *encoded, const char *string, int len)
{
    int i;
    char *p;

    p = encoded;
    for (i = 0; i < len - 2; i += 3) {
    *p++ = basis_64[(string[i] >> 2) & 0x3F];
    *p++ = basis_64[((string[i] & 0x3) << 4) |
                    ((int) (string[i + 1] & 0xF0) >> 4)];
    *p++ = basis_64[((string[i + 1] & 0xF) << 2) |
                    ((int) (string[i + 2] & 0xC0) >> 6)];
    *p++ = basis_64[string[i + 2] & 0x3F];
    }
    if (i < len) {
    *p++ = basis_64[(string[i] >> 2) & 0x3F];
    if (i == (len - 1)) {
        *p++ = basis_64[((string[i] & 0x3) << 4)];
        *p++ = '=';
    }
    else {
        *p++ = basis_64[((string[i] & 0x3) << 4) |
                        ((int) (string[i + 1] & 0xF0) >> 4)];
        *p++ = basis_64[((string[i + 1] & 0xF) << 2)];
    }
    *p++ = '=';
    }

    //*p++ = '\0'; Commented out by MM.
    return p - encoded;
}


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 61), // OctState_t()(void)
/*  1 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  2 */ _CFFI_OP(_CFFI_OP_FUNCTION, 13), // int()(OctInd_t, char *)
/*  3 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // OctInd_t
/*  4 */ _CFFI_OP(_CFFI_OP_POINTER, 25), // char *
/*  5 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  6 */ _CFFI_OP(_CFFI_OP_FUNCTION, 13), // int()(char *, char const *)
/*  7 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/*  8 */ _CFFI_OP(_CFFI_OP_POINTER, 25), // char const *
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 10 */ _CFFI_OP(_CFFI_OP_FUNCTION, 13), // int()(char *, char const *, int)
/* 11 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 12 */ _CFFI_OP(_CFFI_OP_NOOP, 8),
/* 13 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 14 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 15 */ _CFFI_OP(_CFFI_OP_FUNCTION, 13), // int()(char const *)
/* 16 */ _CFFI_OP(_CFFI_OP_NOOP, 8),
/* 17 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION, 13), // int()(int *, char const *, int)
/* 19 */ _CFFI_OP(_CFFI_OP_POINTER, 13), // int *
/* 20 */ _CFFI_OP(_CFFI_OP_NOOP, 8),
/* 21 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 22 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 23 */ _CFFI_OP(_CFFI_OP_FUNCTION, 13), // int()(int *, char)
/* 24 */ _CFFI_OP(_CFFI_OP_NOOP, 19),
/* 25 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 26 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 27 */ _CFFI_OP(_CFFI_OP_FUNCTION, 13), // int()(int)
/* 28 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 29 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 30 */ _CFFI_OP(_CFFI_OP_FUNCTION, 13), // int()(int, char *)
/* 31 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 32 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 33 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 34 */ _CFFI_OP(_CFFI_OP_FUNCTION, 13), // int()(int, char *, int *, char)
/* 35 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 36 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 37 */ _CFFI_OP(_CFFI_OP_NOOP, 19),
/* 38 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2),
/* 39 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 40 */ _CFFI_OP(_CFFI_OP_FUNCTION, 13), // int()(int, int)
/* 41 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 42 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 43 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 44 */ _CFFI_OP(_CFFI_OP_FUNCTION, 13), // int()(int, unsigned int)
/* 45 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 46 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 8), // unsigned int
/* 47 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 48 */ _CFFI_OP(_CFFI_OP_FUNCTION, 13), // int()(void)
/* 49 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 50 */ _CFFI_OP(_CFFI_OP_FUNCTION, 71), // void()(void)
/* 51 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 52 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // MirBlob
/* 53 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // MirBufferStream
/* 54 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // MirConnection
/* 55 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // MirDisplayConfig
/* 56 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 4), // MirPersistentId
/* 57 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 5), // MirPromptSession
/* 58 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 6), // MirScreencast
/* 59 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 7), // MirSurface
/* 60 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 8), // MirSurfaceSpec
/* 61 */ _CFFI_OP(_CFFI_OP_ENUM, 1), // OctState_t
/* 62 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/* 63 */ _CFFI_OP(_CFFI_OP_ARRAY, 25), // char[8]
/* 64 */ (_cffi_opcode_t)(8),
/* 65 */ _CFFI_OP(_CFFI_OP_POINTER, 27), // int(*)(int)
/* 66 */ _CFFI_OP(_CFFI_OP_POINTER, 30), // int(*)(int, char *)
/* 67 */ _CFFI_OP(_CFFI_OP_POINTER, 48), // int(*)(void)
/* 68 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 9), // nv_t
/* 69 */ _CFFI_OP(_CFFI_OP_POINTER, 71), // void *
/* 70 */ _CFFI_OP(_CFFI_OP_POINTER, 50), // void(*)(void)
/* 71 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
/* 72 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 10), // xcb_connection_t
};

static int _cffi_const_Octet0(unsigned long long *o)
{
  int n = (Octet0) <= 0;
  *o = (unsigned long long)((Octet0) | 0);  /* check that Octet0 is an integer */
  return n;
}

static int _cffi_const_Octet1(unsigned long long *o)
{
  int n = (Octet1) <= 0;
  *o = (unsigned long long)((Octet1) | 0);  /* check that Octet1 is an integer */
  return n;
}

static int _cffi_const_Octet2(unsigned long long *o)
{
  int n = (Octet2) <= 0;
  *o = (unsigned long long)((Octet2) | 0);  /* check that Octet2 is an integer */
  return n;
}

static int _cffi_const_firstloop(unsigned long long *o)
{
  int n = (firstloop) <= 0;
  *o = (unsigned long long)((firstloop) | 0);  /* check that firstloop is an integer */
  return n;
}

static int _cffi_const_loopingaround(unsigned long long *o)
{
  int n = (loopingaround) <= 0;
  *o = (unsigned long long)((loopingaround) | 0);  /* check that loopingaround is an integer */
  return n;
}

static int _cffi_const_overwriting(unsigned long long *o)
{
  int n = (overwriting) <= 0;
  *o = (unsigned long long)((overwriting) | 0);  /* check that overwriting is an integer */
  return n;
}

static struct _cffi_externpy_s _cffi_externpy__nt3h_eepromwritedone =
  { "sharedobj.octetpy.nt3h_eepromwritedone", (int)sizeof(int) };

int nt3h_eepromwritedone(void)
{
  char a[8];
  char *p = a;
  _cffi_call_python(&_cffi_externpy__nt3h_eepromwritedone, p);
  return *(int *)p;
}

static struct _cffi_externpy_s _cffi_externpy__nt3h_init =
  { "sharedobj.octetpy.nt3h_init", 0 };

void nt3h_init(void)
{
  char a[8];
  char *p = a;
  _cffi_call_python(&_cffi_externpy__nt3h_init, p);
}

static struct _cffi_externpy_s _cffi_externpy__nt3h_readtag =
  { "sharedobj.octetpy.nt3h_readtag", (int)sizeof(int) };

int nt3h_readtag(int a0, char * a1)
{
  char a[16];
  char *p = a;
  *(int *)(p + 0) = a0;
  *(char * *)(p + 8) = a1;
  _cffi_call_python(&_cffi_externpy__nt3h_readtag, p);
  return *(int *)p;
}

static struct _cffi_externpy_s _cffi_externpy__nt3h_writetag =
  { "sharedobj.octetpy.nt3h_writetag", (int)sizeof(int) };

int nt3h_writetag(int a0, char * a1)
{
  char a[16];
  char *p = a;
  *(int *)(p + 0) = a0;
  *(char * *)(p + 8) = a1;
  _cffi_call_python(&_cffi_externpy__nt3h_writetag, p);
  return *(int *)p;
}

static struct _cffi_externpy_s _cffi_externpy__printint =
  { "sharedobj.octetpy.printint", (int)sizeof(int) };

int printint(int a0)
{
  char a[8];
  char *p = a;
  *(int *)(p + 0) = a0;
  _cffi_call_python(&_cffi_externpy__printint, p);
  return *(int *)p;
}

static int _cffi_d_Base64decode(char * x0, char const * x1)
{
  return Base64decode(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_Base64decode(PyObject *self, PyObject *args)
{
  char * x0;
  char const * x1;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "Base64decode", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(4), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(8), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (char const *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(8), arg1) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = Base64decode(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_Base64decode _cffi_d_Base64decode
#endif

static int _cffi_d_Base64decode_len(char const * x0)
{
  return Base64decode_len(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_Base64decode_len(PyObject *self, PyObject *arg0)
{
  char const * x0;
  Py_ssize_t datasize;
  int result;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(8), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char const *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(8), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = Base64decode_len(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_Base64decode_len _cffi_d_Base64decode_len
#endif

static int _cffi_d_Base64encode(char * x0, char const * x1, int x2)
{
  return Base64encode(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_Base64encode(PyObject *self, PyObject *args)
{
  char * x0;
  char const * x1;
  int x2;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "Base64encode", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(4), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(8), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (char const *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(8), arg1) < 0)
      return NULL;
  }

  x2 = _cffi_to_c_int(arg2, int);
  if (x2 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = Base64encode(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_Base64encode _cffi_d_Base64encode
#endif

static int _cffi_d_Base64encode_len(int x0)
{
  return Base64encode_len(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_Base64encode_len(PyObject *self, PyObject *arg0)
{
  int x0;
  int result;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = Base64encode_len(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_Base64encode_len _cffi_d_Base64encode_len
#endif

static int _cffi_d_eep_cp(int * x0, char const * x1, int x2)
{
  return eep_cp(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_eep_cp(PyObject *self, PyObject *args)
{
  int * x0;
  char const * x1;
  int x2;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "eep_cp", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(19), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (int *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(19), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(8), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (char const *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(8), arg1) < 0)
      return NULL;
  }

  x2 = _cffi_to_c_int(arg2, int);
  if (x2 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = eep_cp(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_eep_cp _cffi_d_eep_cp
#endif

static int _cffi_d_eep_cpbyte(int * x0, char x1)
{
  return eep_cpbyte(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_eep_cpbyte(PyObject *self, PyObject *args)
{
  int * x0;
  char x1;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "eep_cpbyte", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(19), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (int *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(19), arg0) < 0)
      return NULL;
  }

  x1 = (char)_cffi_to_c_char(arg1);
  if (x1 == (char)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = eep_cpbyte(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_eep_cpbyte _cffi_d_eep_cpbyte
#endif

static int _cffi_d_eep_read(int x0, unsigned int x1)
{
  return eep_read(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_eep_read(PyObject *self, PyObject *args)
{
  int x0;
  unsigned int x1;
  int result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "eep_read", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, unsigned int);
  if (x1 == (unsigned int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = eep_read(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_eep_read _cffi_d_eep_read
#endif

static void _cffi_d_eep_waitwritedone(void)
{
  eep_waitwritedone();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_eep_waitwritedone(PyObject *self, PyObject *noarg)
{

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { eep_waitwritedone(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_eep_waitwritedone _cffi_d_eep_waitwritedone
#endif

static int _cffi_d_eep_write(int x0, unsigned int x1)
{
  return eep_write(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_eep_write(PyObject *self, PyObject *args)
{
  int x0;
  unsigned int x1;
  int result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "eep_write", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, unsigned int);
  if (x1 == (unsigned int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = eep_write(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_eep_write _cffi_d_eep_write
#endif

static int _cffi_d_ndef_writeblankurl(int x0, char * x1, int * x2, char x3)
{
  return ndef_writeblankurl(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ndef_writeblankurl(PyObject *self, PyObject *args)
{
  int x0;
  char * x1;
  int * x2;
  char x3;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "ndef_writeblankurl", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (char *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(4), arg1) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(19), arg2, (char **)&x2);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x2 = (int *)alloca((size_t)datasize);
    memset((void *)x2, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x2, _cffi_type(19), arg2) < 0)
      return NULL;
  }

  x3 = (char)_cffi_to_c_char(arg3);
  if (x3 == (char)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ndef_writeblankurl(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_ndef_writeblankurl _cffi_d_ndef_writeblankurl
#endif

static int _cffi_d_ndef_writepreamble(int x0, char * x1)
{
  return ndef_writepreamble(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_ndef_writepreamble(PyObject *self, PyObject *args)
{
  int x0;
  char * x1;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "ndef_writepreamble", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (char *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(4), arg1) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = ndef_writepreamble(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_ndef_writepreamble _cffi_d_ndef_writepreamble
#endif

static int _cffi_d_octet_commit2(void)
{
  return octet_commit2();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_octet_commit2(PyObject *self, PyObject *noarg)
{
  int result;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = octet_commit2(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_octet_commit2 _cffi_d_octet_commit2
#endif

static int _cffi_d_octet_commit4(void)
{
  return octet_commit4();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_octet_commit4(PyObject *self, PyObject *noarg)
{
  int result;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = octet_commit4(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_octet_commit4 _cffi_d_octet_commit4
#endif

static OctState_t _cffi_d_octet_getstate(void)
{
  return octet_getstate();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_octet_getstate(PyObject *self, PyObject *noarg)
{
  OctState_t result;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = octet_getstate(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  return _cffi_from_c_deref((char *)&result, _cffi_type(61));
}
#else
#  define _cffi_f_octet_getstate _cffi_d_octet_getstate
#endif

static int _cffi_d_octet_init(int x0, int x1)
{
  return octet_init(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_octet_init(PyObject *self, PyObject *args)
{
  int x0;
  int x1;
  int result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "octet_init", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = octet_init(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_octet_init _cffi_d_octet_init
#endif

static int _cffi_d_octet_movecursor(void)
{
  return octet_movecursor();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_octet_movecursor(PyObject *self, PyObject *noarg)
{
  int result;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = octet_movecursor(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_octet_movecursor _cffi_d_octet_movecursor
#endif

static void _cffi_d_octet_restore(void)
{
  octet_restore();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_octet_restore(PyObject *self, PyObject *noarg)
{

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { octet_restore(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_octet_restore _cffi_d_octet_restore
#endif

static int _cffi_d_octet_write(OctInd_t x0, char * x1)
{
  return octet_write(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_octet_write(PyObject *self, PyObject *args)
{
  OctInd_t x0;
  char * x1;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "octet_write", 2, 2, &arg0, &arg1))
    return NULL;

  if (_cffi_to_c((char *)&x0, _cffi_type(3), arg0) < 0)
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (char *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(4), arg1) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = octet_write(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_octet_write _cffi_d_octet_write
#endif

_CFFI_UNUSED_FN
static void _cffi_checkfld__nv_t(nv_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char(*tmp)[8] = &p->serial; (void)tmp; }
  { char(*tmp)[8] = &p->seckey; (void)tmp; }
  (void)((p->randstate) | 0);  /* check that 'nv_t.randstate' is an integer */
  (void)((p->smplintervalmins) | 0);  /* check that 'nv_t.smplintervalmins' is an integer */
  (void)((p->sleepintervaldays) | 0);  /* check that 'nv_t.sleepintervaldays' is an integer */
  (void)((p->allwritten) | 0);  /* check that 'nv_t.allwritten' is an integer */
  (void)((p->resetsperloop) | 0);  /* check that 'nv_t.resetsperloop' is an integer */
  (void)((p->resetsalltime) | 0);  /* check that 'nv_t.resetsalltime' is an integer */
}
struct _cffi_align__nv_t { char x; nv_t y; };

static nv_t *_cffi_var_nv(void)
{
  return &(nv);
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "Base64decode", (void *)_cffi_f_Base64decode, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 6), (void *)_cffi_d_Base64decode },
  { "Base64decode_len", (void *)_cffi_f_Base64decode_len, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 15), (void *)_cffi_d_Base64decode_len },
  { "Base64encode", (void *)_cffi_f_Base64encode, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 10), (void *)_cffi_d_Base64encode },
  { "Base64encode_len", (void *)_cffi_f_Base64encode_len, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 27), (void *)_cffi_d_Base64encode_len },
  { "Octet0", (void *)_cffi_const_Octet0, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "Octet1", (void *)_cffi_const_Octet1, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "Octet2", (void *)_cffi_const_Octet2, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "eep_cp", (void *)_cffi_f_eep_cp, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 18), (void *)_cffi_d_eep_cp },
  { "eep_cpbyte", (void *)_cffi_f_eep_cpbyte, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 23), (void *)_cffi_d_eep_cpbyte },
  { "eep_read", (void *)_cffi_f_eep_read, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 44), (void *)_cffi_d_eep_read },
  { "eep_waitwritedone", (void *)_cffi_f_eep_waitwritedone, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 50), (void *)_cffi_d_eep_waitwritedone },
  { "eep_write", (void *)_cffi_f_eep_write, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 44), (void *)_cffi_d_eep_write },
  { "firstloop", (void *)_cffi_const_firstloop, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "loopingaround", (void *)_cffi_const_loopingaround, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ndef_writeblankurl", (void *)_cffi_f_ndef_writeblankurl, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 34), (void *)_cffi_d_ndef_writeblankurl },
  { "ndef_writepreamble", (void *)_cffi_f_ndef_writepreamble, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 30), (void *)_cffi_d_ndef_writepreamble },
  { "nt3h_eepromwritedone", (void *)&_cffi_externpy__nt3h_eepromwritedone, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 67), (void *)nt3h_eepromwritedone },
  { "nt3h_init", (void *)&_cffi_externpy__nt3h_init, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 70), (void *)nt3h_init },
  { "nt3h_readtag", (void *)&_cffi_externpy__nt3h_readtag, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 66), (void *)nt3h_readtag },
  { "nt3h_writetag", (void *)&_cffi_externpy__nt3h_writetag, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 66), (void *)nt3h_writetag },
  { "nv", (void *)_cffi_var_nv, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 68), (void *)0 },
  { "octet_commit2", (void *)_cffi_f_octet_commit2, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 48), (void *)_cffi_d_octet_commit2 },
  { "octet_commit4", (void *)_cffi_f_octet_commit4, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 48), (void *)_cffi_d_octet_commit4 },
  { "octet_getstate", (void *)_cffi_f_octet_getstate, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 0), (void *)_cffi_d_octet_getstate },
  { "octet_init", (void *)_cffi_f_octet_init, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 40), (void *)_cffi_d_octet_init },
  { "octet_movecursor", (void *)_cffi_f_octet_movecursor, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 48), (void *)_cffi_d_octet_movecursor },
  { "octet_restore", (void *)_cffi_f_octet_restore, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 50), (void *)_cffi_d_octet_restore },
  { "octet_write", (void *)_cffi_f_octet_write, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 2), (void *)_cffi_d_octet_write },
  { "overwriting", (void *)_cffi_const_overwriting, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "printint", (void *)&_cffi_externpy__printint, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 65), (void *)printint },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "serial", offsetof(nv_t, serial),
              sizeof(((nv_t *)0)->serial),
              _CFFI_OP(_CFFI_OP_NOOP, 63) },
  { "seckey", offsetof(nv_t, seckey),
              sizeof(((nv_t *)0)->seckey),
              _CFFI_OP(_CFFI_OP_NOOP, 63) },
  { "randstate", offsetof(nv_t, randstate),
                 sizeof(((nv_t *)0)->randstate),
                 _CFFI_OP(_CFFI_OP_NOOP, 46) },
  { "smplintervalmins", offsetof(nv_t, smplintervalmins),
                        sizeof(((nv_t *)0)->smplintervalmins),
                        _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "sleepintervaldays", offsetof(nv_t, sleepintervaldays),
                         sizeof(((nv_t *)0)->sleepintervaldays),
                         _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "allwritten", offsetof(nv_t, allwritten),
                  sizeof(((nv_t *)0)->allwritten),
                  _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "resetsperloop", offsetof(nv_t, resetsperloop),
                     sizeof(((nv_t *)0)->resetsperloop),
                     _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "resetsalltime", offsetof(nv_t, resetsalltime),
                     sizeof(((nv_t *)0)->resetsalltime),
                     _CFFI_OP(_CFFI_OP_NOOP, 13) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "MirBlob", 52, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "MirBufferStream", 53, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "MirConnection", 54, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "MirDisplayConfig", 55, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "MirPersistentId", 56, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "MirPromptSession", 57, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "MirScreencast", 58, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "MirSurface", 59, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "MirSurfaceSpec", 60, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "nvstruct", 68, _CFFI_F_CHECK_FIELDS,
    sizeof(nv_t), offsetof(struct _cffi_align__nv_t, y), 0, 8 },
  { "xcb_connection_t", 72, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "OctInd", 3, _cffi_prim_int(sizeof(OctInd_t), ((OctInd_t)-1) <= 0),
    "Octet0,Octet1,Octet2" },
  { "OctState", 61, _cffi_prim_int(sizeof(OctState_t), ((OctState_t)-1) <= 0),
    "firstloop,loopingaround,overwriting" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "FILE", 13 },
  { "MirBlob", 52 },
  { "MirBufferStream", 53 },
  { "MirConnection", 54 },
  { "MirDisplayConfig", 55 },
  { "MirEGLNativeDisplayType", 69 },
  { "MirEGLNativeWindowType", 69 },
  { "MirPersistentId", 56 },
  { "MirPromptSession", 57 },
  { "MirScreencast", 58 },
  { "MirSurface", 59 },
  { "MirSurfaceSpec", 60 },
  { "OctInd_t", 3 },
  { "OctState_t", 61 },
  { "_LOCK_RECURSIVE_T", 13 },
  { "_LOCK_T", 13 },
  { "__FILE", 13 },
  { "__ULong", 13 },
  { "__builtin_va_list", 13 },
  { "__dev_t", 13 },
  { "__gid_t", 13 },
  { "__gnuc_va_list", 13 },
  { "__int16_t", 13 },
  { "__int32_t", 13 },
  { "__int64_t", 13 },
  { "__int8_t", 13 },
  { "__int_least16_t", 13 },
  { "__int_least32_t", 13 },
  { "__loff_t", 13 },
  { "__off_t", 13 },
  { "__pid_t", 13 },
  { "__s16", 13 },
  { "__s32", 13 },
  { "__s64", 13 },
  { "__s8", 13 },
  { "__sigset_t", 13 },
  { "__tzinfo_type", 13 },
  { "__tzrule_type", 13 },
  { "__u16", 13 },
  { "__u32", 13 },
  { "__u64", 13 },
  { "__u8", 13 },
  { "__uid_t", 13 },
  { "__uint16_t", 13 },
  { "__uint32_t", 13 },
  { "__uint64_t", 13 },
  { "__uint8_t", 13 },
  { "__uint_least16_t", 13 },
  { "__uint_least32_t", 13 },
  { "_flock_t", 13 },
  { "_fpos_t", 13 },
  { "_iconv_t", 13 },
  { "_mbstate_t", 13 },
  { "_off64_t", 13 },
  { "_off_t", 13 },
  { "_sig_func_ptr", 13 },
  { "_ssize_t", 13 },
  { "_types_fd_set", 13 },
  { "bool", 62 },
  { "caddr_t", 13 },
  { "clock_t", 13 },
  { "clockid_t", 13 },
  { "cookie_close_function_t", 13 },
  { "cookie_io_functions_t", 13 },
  { "cookie_read_function_t", 13 },
  { "cookie_seek_function_t", 13 },
  { "cookie_write_function_t", 13 },
  { "daddr_t", 13 },
  { "dev_t", 13 },
  { "div_t", 13 },
  { "fd_mask", 13 },
  { "fpos_t", 13 },
  { "gid_t", 13 },
  { "ino_t", 13 },
  { "int16_t", 13 },
  { "int32_t", 13 },
  { "int64_t", 13 },
  { "int8_t", 13 },
  { "int_fast16_t", 13 },
  { "int_fast32_t", 13 },
  { "int_fast64_t", 13 },
  { "int_fast8_t", 13 },
  { "int_least16_t", 13 },
  { "int_least32_t", 13 },
  { "int_least64_t", 13 },
  { "int_least8_t", 13 },
  { "intmax_t", 13 },
  { "intptr_t", 13 },
  { "jmp_buf", 13 },
  { "key_t", 13 },
  { "ldiv_t", 13 },
  { "lldiv_t", 13 },
  { "mbstate_t", 13 },
  { "mode_t", 13 },
  { "nlink_t", 13 },
  { "nv_t", 68 },
  { "off_t", 13 },
  { "pid_t", 13 },
  { "pthread_attr_t", 13 },
  { "pthread_barrier_t", 13 },
  { "pthread_barrierattr_t", 13 },
  { "pthread_cond_t", 13 },
  { "pthread_condattr_t", 13 },
  { "pthread_key_t", 13 },
  { "pthread_mutex_t", 13 },
  { "pthread_mutexattr_t", 13 },
  { "pthread_once_t", 13 },
  { "pthread_rwlock_t", 13 },
  { "pthread_rwlockattr_t", 13 },
  { "pthread_spinlock_t", 13 },
  { "pthread_t", 13 },
  { "ptrdiff_t", 13 },
  { "rlim_t", 13 },
  { "sa_family_t", 13 },
  { "sem_t", 13 },
  { "sig_atomic_t", 13 },
  { "siginfo_t", 13 },
  { "sigjmp_buf", 13 },
  { "sigset_t", 13 },
  { "size_t", 13 },
  { "ssize_t", 13 },
  { "stack_t", 13 },
  { "suseconds_t", 13 },
  { "time_t", 13 },
  { "timer_t", 13 },
  { "u_char", 13 },
  { "u_int", 13 },
  { "u_long", 13 },
  { "u_short", 13 },
  { "uid_t", 13 },
  { "uint", 13 },
  { "uint16_t", 13 },
  { "uint32_t", 13 },
  { "uint64_t", 13 },
  { "uint8_t", 13 },
  { "uint_fast16_t", 13 },
  { "uint_fast32_t", 13 },
  { "uint_fast64_t", 13 },
  { "uint_fast8_t", 13 },
  { "uint_least16_t", 13 },
  { "uint_least32_t", 13 },
  { "uint_least64_t", 13 },
  { "uint_least8_t", 13 },
  { "uintmax_t", 13 },
  { "uintptr_t", 13 },
  { "useconds_t", 13 },
  { "ushort", 13 },
  { "va_list", 13 },
  { "wchar_t", 13 },
  { "wint_t", 13 },
  { "xcb_connection_t", 72 },
  { "xcb_visualid_t", 13 },
  { "xcb_window_t", 13 },
  { "z_stream", 13 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  30,  /* num_globals */
  11,  /* num_struct_unions */
  2,  /* num_enums */
  154,  /* num_typenames */
  NULL,  /* no includes */
  73,  /* num_types */
  1,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_octetpy(const void *p[])
{
    if (((intptr_t)p[0]) >= 0x0A03) {
        _cffi_call_python_org = (void(*)(struct _cffi_externpy_s *, char *))p[1];
    }
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_octetpy(void) { return NULL; }
#  else
     initoctetpy(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_octetpy(void)
{
  return _cffi_init("sharedobj.octetpy", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initoctetpy(void)
{
  _cffi_init("sharedobj.octetpy", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
