#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   Issue #350 is still open: on Windows, the code here causes it to link
   with PYTHON36.DLL (for example) instead of PYTHON3.DLL.  A fix was
   attempted in 164e526a5515 and 14ce6985e1c3, but reverted: virtualenv
   does not make PYTHON3.DLL available, and so the "correctly" compiled
   version would not run inside a virtualenv.  We will re-apply the fix
   after virtualenv has been fixed for some time.  For explanation, see
   issue #355.  For a workaround if you want PYTHON3.DLL and don't worry
   about virtualenv, see issue #350.  See also 'py_limited_api' in
   setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  include <pyconfig.h>
#  if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG)
#    define Py_LIMITED_API
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t(x);
}


/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

#include "smplhist.h"
#include "defs.h"
#include "md5.h"
#include "nvtype.h"

extern nv_t nv;

int buflensamples = BUFLEN_SAMPLES;
static sdchars_t samplehistory[BUFLEN_SAMPLES];
static int histpos = 0;
static unsigned char md5block[64];
//char secretkey[] = "AAAACCCC";
static const char ipadchar = 0x36;
static const char opadchar = 0x5C;
static MD5_CTX ctx;
static int prevhistpos;

int smplhist_ovr(sdchars_t sample)
{
  samplehistory[prevhistpos] = sample;

  return 0;
}

int smplhist_push(sdchars_t sample)
{
  samplehistory[histpos] = sample;
  prevhistpos = histpos;

  if (histpos == BUFLEN_SAMPLES-1)
  {
    histpos = 0;
  }
  else
  {
    histpos++;
  }

  return 0;
}

static sdchars_t smplhist_read(unsigned int index, int * error)
{
    int readpos;
    sdchars_t sample;
    *error = 0;

    readpos = (histpos - 1) - index;

    if (readpos < 0)
    {
        readpos += (BUFLEN_SAMPLES);
        if (readpos >= histpos)
        {
            sample = samplehistory[readpos];
        }
        else
        {
            sample.m1Msb = 0; // Not allowed to loop around the buffer more than once.
            sample.m2Msb = 0;
            sample.Lsb = 0;
            *error = 1;
        }
    }
    else
    {
        sample = samplehistory[readpos];
    }

    return sample;
}

md5len_t smplhist_md5(int lensmpls, bool usehmac)
{
    sdchars_t prevsmpl;
    int error = 0;
    int smplindex = 0;
    md5len_t md5length;
    unsigned int i;
    unsigned char md5result[16];
    char * secretkey = nv.seckey;


    MD5_Init(&ctx);

    if (usehmac)
    {
        // Append inner key.
        for(i=0; i<sizeof(md5block); i++)
        {
            if (i<SECKEY_LENBYTES)
            {
                md5block[i] = secretkey[i] ^ ipadchar;
            }
            else
            {
                md5block[i] = ipadchar;
            }
        }

        MD5_Update(&ctx, md5block, sizeof(md5block));
    }

    // Seperate sample history into 64 byte blocks and a partial block.
    i=0;
    // Start to take MD5 of the message.
    while(smplindex<lensmpls)
    {
        prevsmpl = smplhist_read(smplindex++, &error);
        if (error == 1)
        {
          for (i=0; i<sizeof(md5length.md5); i++)
          {
              md5length.md5[i] = 9;
          }
          return md5length;
        }
        md5block[i++] = prevsmpl.m1Msb;
        md5block[i++] = prevsmpl.m2Msb;
        md5block[i++] = prevsmpl.Lsb;

        // When i is a multiple of 63 samples, the maximum number that can be store in a 64 byte block.
        if (i == 63)
        {
            MD5_Update(&ctx, md5block, i);
            i = 0;
        }
    }

    if (i > 0)
    {
        // Calculate MD5 checksum from sample history.
        MD5_Update(&ctx, md5block, i);
    }


    if (usehmac)
    {
        // Obtain MD5 digest. Hash sum 1.
        MD5_Final(md5result, &ctx);

        // Copy hash sum 1 to the start of a new MD5 block.
        // Reinitialise MD5.
        MD5_Init(&ctx);

        // Append outer key.
        for(i=0; i<sizeof(md5block); i++)
        {
            if (i<SECKEY_LENBYTES)
            {
                md5block[i] = secretkey[i] ^ opadchar;
            }
            else
            {
                md5block[i] = opadchar;
            }
        }

        MD5_Update(&ctx, md5block, sizeof(md5block));

        for(i=0; i<sizeof(md5result); i++)
        {
            md5block[i] = md5result[i];
        }

        MD5_Update(&ctx, md5block, sizeof(md5result));
    }

    // Obtain MD5 digest.
    MD5_Final(md5result, &ctx);

    // Place lower 6 bytes into md5length structure.
    for (i=0; i<sizeof(md5length.md5); i++)
    {
        md5length.md5[i] = md5result[i];
    }
    md5length.lensmplsbytes[0] = (lensmpls & 0xFF00) >> 8;
    md5length.lensmplsbytes[1] = (lensmpls & 0x00FF);

    return md5length;
}
/*
 * This is an OpenSSL-compatible implementation of the RSA Data Security, Inc.
 * MD5 Message-Digest Algorithm (RFC 1321).
 *
 * Homepage:
 * http://openwall.info/wiki/people/solar/software/public-domain-source-code/md5
 *
 * Author:
 * Alexander Peslyak, better known as Solar Designer <solar at openwall.com>
 *
 * This software was written by Alexander Peslyak in 2001.  No copyright is
 * claimed, and the software is hereby placed in the public domain.
 * In case this attempt to disclaim copyright and place the software in the
 * public domain is deemed null and void, then the software is
 * Copyright (c) 2001 Alexander Peslyak and it is hereby released to the
 * general public under the following terms:
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted.
 *
 * There's ABSOLUTELY NO WARRANTY, express or implied.
 *
 * (This is a heavily cut-down "BSD license".)
 *
 * This differs from Colin Plumb's older public domain implementation in that
 * no exactly 32-bit integer data type is required (any 32-bit or wider
 * unsigned integer data type will do), there's no compile-time endianness
 * configuration, and the function prototypes match OpenSSL's.  No code from
 * Colin Plumb's implementation has been reused; this comment merely compares
 * the properties of the two independent implementations.
 *
 * The primary goals of this implementation are portability and ease of use.
 * It is meant to be fast, but not as fast as possible.  Some known
 * optimizations are not included to reduce source code size and avoid
 * compile-time configuration.
 */

#ifndef HAVE_OPENSSL

#include <string.h>

#include "md5.h"

/*
 * The basic MD5 functions.
 *
 * F and G are optimized compared to their RFC 1321 definitions for
 * architectures that lack an AND-NOT instruction, just like in Colin Plumb's
 * implementation.
 */
#define F(x, y, z)          ((z) ^ ((x) & ((y) ^ (z))))
#define G(x, y, z)          ((y) ^ ((z) & ((x) ^ (y))))
#define H(x, y, z)          (((x) ^ (y)) ^ (z))
#define H2(x, y, z)         ((x) ^ ((y) ^ (z)))
#define I(x, y, z)          ((y) ^ ((x) | ~(z)))

/*
 * The MD5 transformation for all four rounds.
 */
#define STEP(f, a, b, c, d, x, t, s) \
    (a) += f((b), (c), (d)) + (x) + (t); \
    (a) = (((a) << (s)) | (((a) & 0xffffffff) >> (32 - (s)))); \
    (a) += (b);

/*
 * SET reads 4 input bytes in little-endian byte order and stores them in a
 * properly aligned word in host byte order.
 *
 * The check for little-endian architectures that tolerate unaligned memory
 * accesses is just an optimization.  Nothing will break if it fails to detect
 * a suitable architecture.
 *
 * Unfortunately, this optimization may be a C strict aliasing rules violation
 * if the caller's data buffer has effective type that cannot be aliased by
 * MD5_u32plus.  In practice, this problem may occur if these MD5 routines are
 * inlined into a calling function, or with future and dangerously advanced
 * link-time optimizations.  For the time being, keeping these MD5 routines in
 * their own translation unit avoids the problem.
 */
#if defined(__i386__) || defined(__x86_64__) || defined(__vax__)
#define SET(n) \
    (*(MD5_u32plus *)&ptr[(n) * 4])
#define GET(n) \
    SET(n)
#else
#define SET(n) \
    (ctx->block[(n)] = \
    (MD5_u32plus)ptr[(n) * 4] | \
    ((MD5_u32plus)ptr[(n) * 4 + 1] << 8) | \
    ((MD5_u32plus)ptr[(n) * 4 + 2] << 16) | \
    ((MD5_u32plus)ptr[(n) * 4 + 3] << 24))
#define GET(n) \
    (ctx->block[(n)])
#endif

static MD5_u32plus set(int n, MD5_CTX *ctx, unsigned char *ptr)
{
    return SET(n);
}

/*
 * This processes one or more 64-byte data blocks, but does NOT update the bit
 * counters.  There are no alignment requirements.
 */
static const void *body(MD5_CTX *ctx, const void *data, unsigned long size)
{
    const unsigned char *ptr;
    MD5_u32plus a, b, c, d;
    MD5_u32plus saved_a, saved_b, saved_c, saved_d;

    ptr = (const unsigned char *)data;

    a = ctx->a;
    b = ctx->b;
    c = ctx->c;
    d = ctx->d;

    do {
        saved_a = a;
        saved_b = b;
        saved_c = c;
        saved_d = d;

/* Round 1 */
        STEP(F, a, b, c, d, set(0, ctx, ptr), 0xd76aa478, 7)
        STEP(F, d, a, b, c, set(1, ctx, ptr), 0xe8c7b756, 12)
        STEP(F, c, d, a, b, set(2, ctx, ptr), 0x242070db, 17)
        STEP(F, b, c, d, a, set(3, ctx, ptr), 0xc1bdceee, 22)
        STEP(F, a, b, c, d, set(4, ctx, ptr), 0xf57c0faf, 7)
        STEP(F, d, a, b, c, set(5, ctx, ptr), 0x4787c62a, 12)
        STEP(F, c, d, a, b, set(6, ctx, ptr), 0xa8304613, 17)
        STEP(F, b, c, d, a, set(7, ctx, ptr), 0xfd469501, 22)
        STEP(F, a, b, c, d, set(8, ctx, ptr), 0x698098d8, 7)
        STEP(F, d, a, b, c, set(9, ctx, ptr), 0x8b44f7af, 12)
        STEP(F, c, d, a, b, set(10, ctx, ptr), 0xffff5bb1, 17)
        STEP(F, b, c, d, a, set(11, ctx, ptr), 0x895cd7be, 22)
        STEP(F, a, b, c, d, set(12, ctx, ptr), 0x6b901122, 7)
        STEP(F, d, a, b, c, set(13, ctx, ptr), 0xfd987193, 12)
        STEP(F, c, d, a, b, set(14, ctx, ptr), 0xa679438e, 17)
        STEP(F, b, c, d, a, set(15, ctx, ptr), 0x49b40821, 22)

/* Round 2 */
        STEP(G, a, b, c, d, GET(1), 0xf61e2562, 5)
        STEP(G, d, a, b, c, GET(6), 0xc040b340, 9)
        STEP(G, c, d, a, b, GET(11), 0x265e5a51, 14)
        STEP(G, b, c, d, a, GET(0), 0xe9b6c7aa, 20)
        STEP(G, a, b, c, d, GET(5), 0xd62f105d, 5)
        STEP(G, d, a, b, c, GET(10), 0x02441453, 9)
        STEP(G, c, d, a, b, GET(15), 0xd8a1e681, 14)
        STEP(G, b, c, d, a, GET(4), 0xe7d3fbc8, 20)
        STEP(G, a, b, c, d, GET(9), 0x21e1cde6, 5)
        STEP(G, d, a, b, c, GET(14), 0xc33707d6, 9)
        STEP(G, c, d, a, b, GET(3), 0xf4d50d87, 14)
        STEP(G, b, c, d, a, GET(8), 0x455a14ed, 20)
        STEP(G, a, b, c, d, GET(13), 0xa9e3e905, 5)
        STEP(G, d, a, b, c, GET(2), 0xfcefa3f8, 9)
        STEP(G, c, d, a, b, GET(7), 0x676f02d9, 14)
        STEP(G, b, c, d, a, GET(12), 0x8d2a4c8a, 20)

/* Round 3 */
        STEP(H, a, b, c, d, GET(5), 0xfffa3942, 4)
        STEP(H2, d, a, b, c, GET(8), 0x8771f681, 11)
        STEP(H, c, d, a, b, GET(11), 0x6d9d6122, 16)
        STEP(H2, b, c, d, a, GET(14), 0xfde5380c, 23)
        STEP(H, a, b, c, d, GET(1), 0xa4beea44, 4)
        STEP(H2, d, a, b, c, GET(4), 0x4bdecfa9, 11)
        STEP(H, c, d, a, b, GET(7), 0xf6bb4b60, 16)
        STEP(H2, b, c, d, a, GET(10), 0xbebfbc70, 23)
        STEP(H, a, b, c, d, GET(13), 0x289b7ec6, 4)
        STEP(H2, d, a, b, c, GET(0), 0xeaa127fa, 11)
        STEP(H, c, d, a, b, GET(3), 0xd4ef3085, 16)
        STEP(H2, b, c, d, a, GET(6), 0x04881d05, 23)
        STEP(H, a, b, c, d, GET(9), 0xd9d4d039, 4)
        STEP(H2, d, a, b, c, GET(12), 0xe6db99e5, 11)
        STEP(H, c, d, a, b, GET(15), 0x1fa27cf8, 16)
        STEP(H2, b, c, d, a, GET(2), 0xc4ac5665, 23)

/* Round 4 */
        STEP(I, a, b, c, d, GET(0), 0xf4292244, 6)
        STEP(I, d, a, b, c, GET(7), 0x432aff97, 10)
        STEP(I, c, d, a, b, GET(14), 0xab9423a7, 15)
        STEP(I, b, c, d, a, GET(5), 0xfc93a039, 21)
        STEP(I, a, b, c, d, GET(12), 0x655b59c3, 6)
        STEP(I, d, a, b, c, GET(3), 0x8f0ccc92, 10)
        STEP(I, c, d, a, b, GET(10), 0xffeff47d, 15)
        STEP(I, b, c, d, a, GET(1), 0x85845dd1, 21)
        STEP(I, a, b, c, d, GET(8), 0x6fa87e4f, 6)
        STEP(I, d, a, b, c, GET(15), 0xfe2ce6e0, 10)
        STEP(I, c, d, a, b, GET(6), 0xa3014314, 15)
        STEP(I, b, c, d, a, GET(13), 0x4e0811a1, 21)
        STEP(I, a, b, c, d, GET(4), 0xf7537e82, 6)
        STEP(I, d, a, b, c, GET(11), 0xbd3af235, 10)
        STEP(I, c, d, a, b, GET(2), 0x2ad7d2bb, 15)
        STEP(I, b, c, d, a, GET(9), 0xeb86d391, 21)

        a += saved_a;
        b += saved_b;
        c += saved_c;
        d += saved_d;

        ptr += 64;
    } while (size -= 64);

    ctx->a = a;
    ctx->b = b;
    ctx->c = c;
    ctx->d = d;

    return ptr;
}

void MD5_Init(MD5_CTX *ctx)
{
    ctx->a = 0x67452301;
    ctx->b = 0xefcdab89;
    ctx->c = 0x98badcfe;
    ctx->d = 0x10325476;

    ctx->lo = 0;
    ctx->hi = 0;
}

void MD5_Update(MD5_CTX *ctx, const void *data, unsigned long size)
{
    MD5_u32plus saved_lo;
    unsigned long used, available;

    saved_lo = ctx->lo;
    if ((ctx->lo = (saved_lo + size) & 0x1fffffff) < saved_lo)
        ctx->hi++;
    ctx->hi += size >> 29;

    used = saved_lo & 0x3f;

    if (used) {
        available = 64 - used;

        if (size < available) {
            memcpy(&ctx->buffer[used], data, size);
            return;
        }

        memcpy(&ctx->buffer[used], data, available);
        data = (const unsigned char *)data + available;
        size -= available;
        body(ctx, ctx->buffer, 64);
    }

    if (size >= 64) {
        data = body(ctx, data, size & ~(unsigned long)0x3f);
        size &= 0x3f;
    }

    memcpy(ctx->buffer, data, size);
}

#define OUT(dst, src) \
    (dst)[0] = (unsigned char)(src); \
    (dst)[1] = (unsigned char)((src) >> 8); \
    (dst)[2] = (unsigned char)((src) >> 16); \
    (dst)[3] = (unsigned char)((src) >> 24);

void MD5_Final(unsigned char *result, MD5_CTX *ctx)
{
    unsigned long used, available;

    used = ctx->lo & 0x3f;

    ctx->buffer[used++] = 0x80;

    available = 64 - used;

    if (available < 8) {
        memset(&ctx->buffer[used], 0, available);
        body(ctx, ctx->buffer, 64);
        used = 0;
        available = 64;
    }

    memset(&ctx->buffer[used], 0, available - 8);

    ctx->lo <<= 3;
    OUT(&ctx->buffer[56], ctx->lo)
    OUT(&ctx->buffer[60], ctx->hi)

    body(ctx, ctx->buffer, 64);

    OUT(&result[0], ctx->a)
    OUT(&result[4], ctx->b)
    OUT(&result[8], ctx->c)
    OUT(&result[12], ctx->d)

    memset(ctx, 0, sizeof(*ctx));
}

#endif


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 4), // int()(sdchars_t)
/*  1 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 12), // sdchars_t
/*  2 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  3 */ _CFFI_OP(_CFFI_OP_FUNCTION, 32), // md5len_t()(int, _Bool)
/*  4 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/*  5 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/*  6 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION, 45), // void()(MD5_CTX *)
/*  8 */ _CFFI_OP(_CFFI_OP_POINTER, 19), // MD5_CTX *
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 10 */ _CFFI_OP(_CFFI_OP_FUNCTION, 45), // void()(MD5_CTX *, void const *, unsigned long)
/* 11 */ _CFFI_OP(_CFFI_OP_NOOP, 8),
/* 12 */ _CFFI_OP(_CFFI_OP_POINTER, 45), // void const *
/* 13 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 10), // unsigned long
/* 14 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 15 */ _CFFI_OP(_CFFI_OP_FUNCTION, 45), // void()(unsigned char *, MD5_CTX *)
/* 16 */ _CFFI_OP(_CFFI_OP_POINTER, 34), // unsigned char *
/* 17 */ _CFFI_OP(_CFFI_OP_NOOP, 8),
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 19 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // MD5_CTX
/* 20 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // MirBlob
/* 21 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // MirBufferStream
/* 22 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // MirConnection
/* 23 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 4), // MirDisplayConfig
/* 24 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 5), // MirPersistentId
/* 25 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 6), // MirPromptSession
/* 26 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 7), // MirScreencast
/* 27 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 8), // MirSurface
/* 28 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 9), // MirSurfaceSpec
/* 29 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 30 */ _CFFI_OP(_CFFI_OP_ARRAY, 29), // char[8]
/* 31 */ (_cffi_opcode_t)(8),
/* 32 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 10), // md5len_t
/* 33 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 11), // nv_t
/* 34 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 4), // unsigned char
/* 35 */ _CFFI_OP(_CFFI_OP_ARRAY, 34), // unsigned char[2]
/* 36 */ (_cffi_opcode_t)(2),
/* 37 */ _CFFI_OP(_CFFI_OP_ARRAY, 34), // unsigned char[64]
/* 38 */ (_cffi_opcode_t)(64),
/* 39 */ _CFFI_OP(_CFFI_OP_ARRAY, 34), // unsigned char[7]
/* 40 */ (_cffi_opcode_t)(7),
/* 41 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 8), // unsigned int
/* 42 */ _CFFI_OP(_CFFI_OP_ARRAY, 13), // unsigned long[16]
/* 43 */ (_cffi_opcode_t)(16),
/* 44 */ _CFFI_OP(_CFFI_OP_POINTER, 45), // void *
/* 45 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
/* 46 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 13), // xcb_connection_t
};

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_MD5_CTX(MD5_CTX *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->lo) | 0);  /* check that 'MD5_CTX.lo' is an integer */
  (void)((p->hi) | 0);  /* check that 'MD5_CTX.hi' is an integer */
  (void)((p->a) | 0);  /* check that 'MD5_CTX.a' is an integer */
  (void)((p->b) | 0);  /* check that 'MD5_CTX.b' is an integer */
  (void)((p->c) | 0);  /* check that 'MD5_CTX.c' is an integer */
  (void)((p->d) | 0);  /* check that 'MD5_CTX.d' is an integer */
  { unsigned char(*tmp)[64] = &p->buffer; (void)tmp; }
  { unsigned long(*tmp)[16] = &p->block; (void)tmp; }
}
struct _cffi_align_typedef_MD5_CTX { char x; MD5_CTX y; };

static void _cffi_d_MD5_Final(unsigned char * x0, MD5_CTX * x1)
{
  MD5_Final(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_MD5_Final(PyObject *self, PyObject *args)
{
  unsigned char * x0;
  MD5_CTX * x1;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "MD5_Final", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(16), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (unsigned char *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(16), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(8), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (MD5_CTX *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(8), arg1) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { MD5_Final(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_MD5_Final _cffi_d_MD5_Final
#endif

static void _cffi_d_MD5_Init(MD5_CTX * x0)
{
  MD5_Init(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_MD5_Init(PyObject *self, PyObject *arg0)
{
  MD5_CTX * x0;
  Py_ssize_t datasize;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(8), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (MD5_CTX *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(8), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { MD5_Init(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_MD5_Init _cffi_d_MD5_Init
#endif

static void _cffi_d_MD5_Update(MD5_CTX * x0, void const * x1, unsigned long x2)
{
  MD5_Update(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_MD5_Update(PyObject *self, PyObject *args)
{
  MD5_CTX * x0;
  void const * x1;
  unsigned long x2;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "MD5_Update", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(8), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (MD5_CTX *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(8), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(12), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (void const *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(12), arg1) < 0)
      return NULL;
  }

  x2 = _cffi_to_c_int(arg2, unsigned long);
  if (x2 == (unsigned long)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { MD5_Update(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_MD5_Update _cffi_d_MD5_Update
#endif

static md5len_t _cffi_d_smplhist_md5(int x0, _Bool x1)
{
  return smplhist_md5(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_smplhist_md5(PyObject *self, PyObject *args)
{
  int x0;
  _Bool x1;
  md5len_t result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "smplhist_md5", 2, 2, &arg0, &arg1))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  x1 = (_Bool)_cffi_to_c__Bool(arg1);
  if (x1 == (_Bool)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = smplhist_md5(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_struct((char *)&result, _cffi_type(32));
}
#else
static void _cffi_f_smplhist_md5(md5len_t *result, int x0, _Bool x1)
{
  { *result = smplhist_md5(x0, x1); }
}
#endif

static int _cffi_d_smplhist_ovr(sdchars_t x0)
{
  return smplhist_ovr(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_smplhist_ovr(PyObject *self, PyObject *arg0)
{
  sdchars_t x0;
  int result;

  if (_cffi_to_c((char *)&x0, _cffi_type(1), arg0) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = smplhist_ovr(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
static int _cffi_f_smplhist_ovr(sdchars_t *x0)
{
  int result;
  { result = smplhist_ovr(*x0); }
  return result;
}
#endif

static int _cffi_d_smplhist_push(sdchars_t x0)
{
  return smplhist_push(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_smplhist_push(PyObject *self, PyObject *arg0)
{
  sdchars_t x0;
  int result;

  if (_cffi_to_c((char *)&x0, _cffi_type(1), arg0) < 0)
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = smplhist_push(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
static int _cffi_f_smplhist_push(sdchars_t *x0)
{
  int result;
  { result = smplhist_push(*x0); }
  return result;
}
#endif

_CFFI_UNUSED_FN
static void _cffi_checkfld__md5len_t(md5len_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { unsigned char(*tmp)[7] = &p->md5; (void)tmp; }
  { unsigned char(*tmp)[2] = &p->lensmplsbytes; (void)tmp; }
}
struct _cffi_align__md5len_t { char x; md5len_t y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__nv_t(nv_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char(*tmp)[8] = &p->serial; (void)tmp; }
  { char(*tmp)[8] = &p->seckey; (void)tmp; }
  (void)((p->randstate) | 0);  /* check that 'nv_t.randstate' is an integer */
  (void)((p->smplintervalmins) | 0);  /* check that 'nv_t.smplintervalmins' is an integer */
  (void)((p->sleepintervaldays) | 0);  /* check that 'nv_t.sleepintervaldays' is an integer */
  (void)((p->allwritten) | 0);  /* check that 'nv_t.allwritten' is an integer */
  (void)((p->resetsperloop) | 0);  /* check that 'nv_t.resetsperloop' is an integer */
  (void)((p->resetsalltime) | 0);  /* check that 'nv_t.resetsalltime' is an integer */
}
struct _cffi_align__nv_t { char x; nv_t y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__sdchars_t(sdchars_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->m1Msb) | 0);  /* check that 'sdchars_t.m1Msb' is an integer */
  (void)((p->m2Msb) | 0);  /* check that 'sdchars_t.m2Msb' is an integer */
  (void)((p->Lsb) | 0);  /* check that 'sdchars_t.Lsb' is an integer */
}
struct _cffi_align__sdchars_t { char x; sdchars_t y; };

static nv_t *_cffi_var_nv(void)
{
  return &(nv);
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "MD5_Final", (void *)_cffi_f_MD5_Final, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 15), (void *)_cffi_d_MD5_Final },
  { "MD5_Init", (void *)_cffi_f_MD5_Init, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 7), (void *)_cffi_d_MD5_Init },
  { "MD5_Update", (void *)_cffi_f_MD5_Update, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 10), (void *)_cffi_d_MD5_Update },
  { "nv", (void *)_cffi_var_nv, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 33), (void *)0 },
  { "smplhist_md5", (void *)_cffi_f_smplhist_md5, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 3), (void *)_cffi_d_smplhist_md5 },
  { "smplhist_ovr", (void *)_cffi_f_smplhist_ovr, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 0), (void *)_cffi_d_smplhist_ovr },
  { "smplhist_push", (void *)_cffi_f_smplhist_push, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 0), (void *)_cffi_d_smplhist_push },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "lo", offsetof(MD5_CTX, lo),
          sizeof(((MD5_CTX *)0)->lo),
          _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "hi", offsetof(MD5_CTX, hi),
          sizeof(((MD5_CTX *)0)->hi),
          _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "a", offsetof(MD5_CTX, a),
         sizeof(((MD5_CTX *)0)->a),
         _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "b", offsetof(MD5_CTX, b),
         sizeof(((MD5_CTX *)0)->b),
         _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "c", offsetof(MD5_CTX, c),
         sizeof(((MD5_CTX *)0)->c),
         _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "d", offsetof(MD5_CTX, d),
         sizeof(((MD5_CTX *)0)->d),
         _CFFI_OP(_CFFI_OP_NOOP, 13) },
  { "buffer", offsetof(MD5_CTX, buffer),
              sizeof(((MD5_CTX *)0)->buffer),
              _CFFI_OP(_CFFI_OP_NOOP, 37) },
  { "block", offsetof(MD5_CTX, block),
             sizeof(((MD5_CTX *)0)->block),
             _CFFI_OP(_CFFI_OP_NOOP, 42) },
  { "md5", offsetof(md5len_t, md5),
           sizeof(((md5len_t *)0)->md5),
           _CFFI_OP(_CFFI_OP_NOOP, 39) },
  { "lensmplsbytes", offsetof(md5len_t, lensmplsbytes),
                     sizeof(((md5len_t *)0)->lensmplsbytes),
                     _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "serial", offsetof(nv_t, serial),
              sizeof(((nv_t *)0)->serial),
              _CFFI_OP(_CFFI_OP_NOOP, 30) },
  { "seckey", offsetof(nv_t, seckey),
              sizeof(((nv_t *)0)->seckey),
              _CFFI_OP(_CFFI_OP_NOOP, 30) },
  { "randstate", offsetof(nv_t, randstate),
                 sizeof(((nv_t *)0)->randstate),
                 _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "smplintervalmins", offsetof(nv_t, smplintervalmins),
                        sizeof(((nv_t *)0)->smplintervalmins),
                        _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "sleepintervaldays", offsetof(nv_t, sleepintervaldays),
                         sizeof(((nv_t *)0)->sleepintervaldays),
                         _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "allwritten", offsetof(nv_t, allwritten),
                  sizeof(((nv_t *)0)->allwritten),
                  _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "resetsperloop", offsetof(nv_t, resetsperloop),
                     sizeof(((nv_t *)0)->resetsperloop),
                     _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "resetsalltime", offsetof(nv_t, resetsalltime),
                     sizeof(((nv_t *)0)->resetsalltime),
                     _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "m1Msb", offsetof(sdchars_t, m1Msb),
             sizeof(((sdchars_t *)0)->m1Msb),
             _CFFI_OP(_CFFI_OP_NOOP, 34) },
  { "m2Msb", offsetof(sdchars_t, m2Msb),
             sizeof(((sdchars_t *)0)->m2Msb),
             _CFFI_OP(_CFFI_OP_NOOP, 34) },
  { "Lsb", offsetof(sdchars_t, Lsb),
           sizeof(((sdchars_t *)0)->Lsb),
           _CFFI_OP(_CFFI_OP_NOOP, 34) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "$MD5_CTX", 19, _CFFI_F_CHECK_FIELDS,
    sizeof(MD5_CTX), offsetof(struct _cffi_align_typedef_MD5_CTX, y), 0, 8 },
  { "MirBlob", 20, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "MirBufferStream", 21, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "MirConnection", 22, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "MirDisplayConfig", 23, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "MirPersistentId", 24, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "MirPromptSession", 25, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "MirScreencast", 26, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "MirSurface", 27, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "MirSurfaceSpec", 28, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "md5len", 32, _CFFI_F_CHECK_FIELDS,
    sizeof(md5len_t), offsetof(struct _cffi_align__md5len_t, y), 8, 2 },
  { "nvstruct", 33, _CFFI_F_CHECK_FIELDS,
    sizeof(nv_t), offsetof(struct _cffi_align__nv_t, y), 10, 8 },
  { "sensordatachars", 1, _CFFI_F_CHECK_FIELDS,
    sizeof(sdchars_t), offsetof(struct _cffi_align__sdchars_t, y), 18, 3 },
  { "xcb_connection_t", 46, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "FILE", 4 },
  { "MD5_CTX", 19 },
  { "MD5_u32plus", 13 },
  { "MirBlob", 20 },
  { "MirBufferStream", 21 },
  { "MirConnection", 22 },
  { "MirDisplayConfig", 23 },
  { "MirEGLNativeDisplayType", 44 },
  { "MirEGLNativeWindowType", 44 },
  { "MirPersistentId", 24 },
  { "MirPromptSession", 25 },
  { "MirScreencast", 26 },
  { "MirSurface", 27 },
  { "MirSurfaceSpec", 28 },
  { "_LOCK_RECURSIVE_T", 4 },
  { "_LOCK_T", 4 },
  { "__FILE", 4 },
  { "__ULong", 4 },
  { "__builtin_va_list", 4 },
  { "__dev_t", 4 },
  { "__gid_t", 4 },
  { "__gnuc_va_list", 4 },
  { "__int16_t", 4 },
  { "__int32_t", 4 },
  { "__int64_t", 4 },
  { "__int8_t", 4 },
  { "__int_least16_t", 4 },
  { "__int_least32_t", 4 },
  { "__loff_t", 4 },
  { "__off_t", 4 },
  { "__pid_t", 4 },
  { "__s16", 4 },
  { "__s32", 4 },
  { "__s64", 4 },
  { "__s8", 4 },
  { "__sigset_t", 4 },
  { "__tzinfo_type", 4 },
  { "__tzrule_type", 4 },
  { "__u16", 4 },
  { "__u32", 4 },
  { "__u64", 4 },
  { "__u8", 4 },
  { "__uid_t", 4 },
  { "__uint16_t", 4 },
  { "__uint32_t", 4 },
  { "__uint64_t", 4 },
  { "__uint8_t", 4 },
  { "__uint_least16_t", 4 },
  { "__uint_least32_t", 4 },
  { "_flock_t", 4 },
  { "_fpos_t", 4 },
  { "_iconv_t", 4 },
  { "_mbstate_t", 4 },
  { "_off64_t", 4 },
  { "_off_t", 4 },
  { "_sig_func_ptr", 4 },
  { "_ssize_t", 4 },
  { "_types_fd_set", 4 },
  { "bool", 5 },
  { "caddr_t", 4 },
  { "clock_t", 4 },
  { "clockid_t", 4 },
  { "cookie_close_function_t", 4 },
  { "cookie_io_functions_t", 4 },
  { "cookie_read_function_t", 4 },
  { "cookie_seek_function_t", 4 },
  { "cookie_write_function_t", 4 },
  { "daddr_t", 4 },
  { "dev_t", 4 },
  { "div_t", 4 },
  { "fd_mask", 4 },
  { "fpos_t", 4 },
  { "gid_t", 4 },
  { "ino_t", 4 },
  { "int16_t", 4 },
  { "int32_t", 4 },
  { "int64_t", 4 },
  { "int8_t", 4 },
  { "int_fast16_t", 4 },
  { "int_fast32_t", 4 },
  { "int_fast64_t", 4 },
  { "int_fast8_t", 4 },
  { "int_least16_t", 4 },
  { "int_least32_t", 4 },
  { "int_least64_t", 4 },
  { "int_least8_t", 4 },
  { "intmax_t", 4 },
  { "intptr_t", 4 },
  { "jmp_buf", 4 },
  { "key_t", 4 },
  { "ldiv_t", 4 },
  { "lldiv_t", 4 },
  { "mbstate_t", 4 },
  { "md5len_t", 32 },
  { "mode_t", 4 },
  { "nlink_t", 4 },
  { "nv_t", 33 },
  { "off_t", 4 },
  { "pid_t", 4 },
  { "pthread_attr_t", 4 },
  { "pthread_barrier_t", 4 },
  { "pthread_barrierattr_t", 4 },
  { "pthread_cond_t", 4 },
  { "pthread_condattr_t", 4 },
  { "pthread_key_t", 4 },
  { "pthread_mutex_t", 4 },
  { "pthread_mutexattr_t", 4 },
  { "pthread_once_t", 4 },
  { "pthread_rwlock_t", 4 },
  { "pthread_rwlockattr_t", 4 },
  { "pthread_spinlock_t", 4 },
  { "pthread_t", 4 },
  { "ptrdiff_t", 4 },
  { "rlim_t", 4 },
  { "sa_family_t", 4 },
  { "sdchars_t", 1 },
  { "sem_t", 4 },
  { "sig_atomic_t", 4 },
  { "siginfo_t", 4 },
  { "sigjmp_buf", 4 },
  { "sigset_t", 4 },
  { "size_t", 4 },
  { "ssize_t", 4 },
  { "stack_t", 4 },
  { "suseconds_t", 4 },
  { "time_t", 4 },
  { "timer_t", 4 },
  { "u_char", 4 },
  { "u_int", 4 },
  { "u_long", 4 },
  { "u_short", 4 },
  { "uid_t", 4 },
  { "uint", 4 },
  { "uint16_t", 4 },
  { "uint32_t", 4 },
  { "uint64_t", 4 },
  { "uint8_t", 4 },
  { "uint_fast16_t", 4 },
  { "uint_fast32_t", 4 },
  { "uint_fast64_t", 4 },
  { "uint_fast8_t", 4 },
  { "uint_least16_t", 4 },
  { "uint_least32_t", 4 },
  { "uint_least64_t", 4 },
  { "uint_least8_t", 4 },
  { "uintmax_t", 4 },
  { "uintptr_t", 4 },
  { "useconds_t", 4 },
  { "ushort", 4 },
  { "va_list", 4 },
  { "wchar_t", 4 },
  { "wint_t", 4 },
  { "xcb_connection_t", 46 },
  { "xcb_visualid_t", 4 },
  { "xcb_window_t", 4 },
  { "z_stream", 4 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  NULL,  /* no enums */
  _cffi_typenames,
  7,  /* num_globals */
  14,  /* num_struct_unions */
  0,  /* num_enums */
  156,  /* num_typenames */
  NULL,  /* no includes */
  47,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_smplhistpy(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_smplhistpy(void) { return NULL; }
#  else
     initsmplhistpy(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_smplhistpy(void)
{
  return _cffi_init("sharedobj.smplhistpy", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initsmplhistpy(void)
{
  _cffi_init("sharedobj.smplhistpy", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
